# Basics Numpy

In [124]:
print("Yash Uttam")

Yash Uttam


In [2]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])   # Create array from list
arr

array([1, 2, 3, 4, 5])

In [9]:
a = [1,2,3,4,5,5.5]

In [10]:
np.array(a)

array([1. , 2. , 3. , 4. , 5. , 5.5])

In [15]:
arr = [[1,2,3],[4,5,6],[7,8,9]]   # Create Matrix
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(11)   # get Sequence

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.linspace(1,20,5)  # Distribute in equal parts

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [28]:
np.linspace(1,2,6)  # Distribute in equal parts

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

### Random Variable

In [198]:
np.random.rand(5)  # 0 to 1

array([0.26107315, 0.67786217, 0.48007424, 0.43004483, 0.36743146])

In [35]:
np.random.randn(12)  # Range -3 to +3

array([-0.42330869, -0.68449365,  0.41132463, -0.21930165, -1.09535577,
       -2.64303489,  0.47762439,  1.04614688,  0.90782718, -1.1293987 ,
       -0.52641621,  2.45162269])

In [38]:
np.random.randint(1,20,10)

array([ 5,  8, 10, 12, 15,  4, 14, 19,  3,  6], dtype=int32)

### Attribute

In [39]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
type(arr)

list

In [48]:
arr = np.array(arr)

In [49]:
arr.shape  # Row - Coloum

(3, 3)

In [50]:
arr.size   # Value count

9

In [52]:
arr.dtype

dtype('int64')

### Methods

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr.std()

np.float64(2.581988897471611)

In [57]:
arr.mean()

np.float64(5.0)

In [58]:
arr.max()

np.int64(9)

In [59]:
arr.argmax()

np.int64(8)

In [61]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
arr = arr.reshape(4,5)  # Check value count are same then apply
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Intermideate

In [66]:
arr= np.arange(20) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
arr[2:20:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [74]:
arr[::-3]

array([19, 16, 13, 10,  7,  4,  1])

In [76]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
print(arr[1])
arr[4]

[5 6 7 8 9]


array([20, 21, 22, 23, 24])

In [83]:
arr[2,2]

np.int64(12)

In [84]:
arr[2:6,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [85]:
arr[0:6,3:4]    # Or [:,3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [86]:
arr[:,3]

array([ 3,  8, 13, 18, 23])

### Bool Indexing

In [94]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [95]:
boolvalue = arr % 2 == 0
boolvalue

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [96]:
arr = arr[boolvalue] # Hold only true value position
arr

array([12, 14, 16, 18, 20])

## Array Operation

In [111]:
a1 = np.array(np.arange(1,6))
a2 = np.array(np.arange(6,11))
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [113]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [114]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [115]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [117]:
a2//a1

array([6, 3, 2, 2, 2])

In [119]:
a2**a1   

array([     6,     49,    512,   6561, 100000])

In [121]:
a2 + 10000000000

array([10000000006, 10000000007, 10000000008, 10000000009, 10000000010])

In [122]:
a2 ** 3

array([ 216,  343,  512,  729, 1000])

In [123]:
import numpy as np

In [161]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [162]:
slice = a[1:5]   # Slicing
slice = slice * 100
slice

array([100, 200, 300, 400])

In [163]:
b=a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [164]:
slice[2] = 9999
slice

array([ 100,  200, 9999,  400])

In [180]:
a = [10,20,30]
b= a.copy()
b

[10, 20, 30]

In [181]:
b[1]= 555

In [182]:
b

[10, 555, 30]

In [183]:
a

[10, 20, 30]

## Matrix Operation

In [185]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [186]:
a

array([[1, 2],
       [3, 4]])

In [187]:
b

array([[5, 6],
       [7, 8]])

In [189]:
a @ b #Dot Product

array([[19, 22],
       [43, 50]])

In [191]:
a.T # Transpose

array([[1, 3],
       [2, 4]])

In [192]:
a*b # Cross Product

array([[ 5, 12],
       [21, 32]])

In [193]:
a + b # Addition

array([[ 6,  8],
       [10, 12]])

# Advance

In [200]:
import numpy as np

In [216]:
a = np.array(np.arange(1,6))
b = np.array(np.arange(5,10))

In [217]:
a

array([1, 2, 3, 4, 5])

In [218]:
b

array([5, 6, 7, 8, 9])

In [219]:
np.hstack((a,b))    # Horizontal Merge (Append)

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [220]:
np.column_stack((a,b))   # Horizontal Merge

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [221]:
np.vstack((a,b))    # Vertcal merge

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [225]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [234]:
np.hsplit(arr,2)     # Devide equal parts in horizontal

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [235]:
a = np.vsplit(arr,1)   # Devide Equal Parts verticly
a

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [237]:
for i in a:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Continue . . . . . ....